trainer: 
  max_epochs: 50
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        project: petal
        offline: false
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 3
        monitor: validation_f1
        mode: max
        dirpath: model_checkpoints
        filename: {epoch:02d}-{validation_f1:.2f}
model:
  n_output: 6
