# Configure this
EXPERIMENT_NAME=e07225c459f808471e9cafb4e2c87b7e
EXPERIMENT_VERSION=version_1
CHECKPOINT_NAME="epoch=40-validation_f1=0.52"

EXPERIMENTS_PATH=ml/experiments
EXPERIMENT_PATH=$EXPERIMENTS_PATH/$EXPERIMENT_NAME
CHECKPOINT_PATH=$EXPERIMENT_PATH/$EXPERIMENT_VERSION/checkpoints/$CHECKPOINT_NAME.ckpt

python -m ml.clis.vision_cnn_cli test --config=$EXPERIMENT_PATH/config.yaml --ckpt_path=$CHECKPOINT_PATH
