trainer: 
  max_epochs: 50
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args: 
        project: petal
        offline: false
        save_dir: ml/experiments
    - class_path: lightning.pytorch.loggers.CSVLogger
  callbacks:
    class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      #dirpath: experiments/experiment1/checkpoints  # Save checkpoints here
      save_top_k: 3
      monitor: validation_f1
      filename: "{epoch:02d}-{validation_f1:.2f}"
      mode: max
model:
  n_output: 6 
  lr: 0.001
  freeze: true
