trainer:
  callbacks:
    class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      filename: '{epoch:02d}-{validation_macro_f1:.2f}'
      mode: max
      monitor: validation_macro_f1
      save_top_k: 3
  logger:
  - class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      offline: false
      project: petal
      save_dir: ml/experiments
  - class_path: lightning.pytorch.loggers.CSVLogger
  max_epochs: 50
data:
  init_args:
    batch_size: 64
    number_of_workers: 15
    seed: 42
    train_ratio: 0.7
    validation_ratio: 0.1
    verbose: false