data:
  class_path: ml.data.modules.CNNetDataModule
  init_args:
    binary: true 
    dataset_type: pre-labeled
    spectrogram_backend: torch
    spectrogram_type: spectrogram
model:
  class_path: ml.models.CNNet
  init_args:
    n_output: 1
    lr: 0.001
