auto_lr_find: true
trainer:
  callbacks:
    class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      filename: '{epoch:02d}-{validation_f1:.2f}'
      mode: max
      monitor: validation_f1
      save_top_k: 3
  logger:
  - class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      offline: false
      project: petal
      save_dir: ml/experiments
  - class_path: lightning.pytorch.loggers.CSVLogger
  max_epochs: 50
data:
  batch_size: 16
  number_of_workers: 5
  seed: 42
  train_ratio: 0.7
  validation_ratio: 0.1
  verbose: false
  dataset_type: post-labeled
  pretrained_model_name: resnet50
  spectrogram_type: spectrogram
model:
  freeze: false
  n_output: 6
  pretrained_model_name: resnet50

