data:
  class_path: ml.data.modules.VisionDataModule
  init_args:
    dataset_type: pre-labeled
    pretrained_model_name: resnet50
    spectrogram_backend: torch
    spectrogram_type: spectrogram
model:
  class_path: ml.models.VisionCNN
  init_args:
    freeze: false
    n_output: 7
    lr: 0.0001
    pretrained_model_name: resnet50
    weigh_loss: true
