data:
  class_path: ml.data.modules.VisionDataModule
  init_args:
    binary: true
    dataset_type: pre-labeled
    desired_distribution: {'neutral': 0.5, 'not-neutral': 0.5}
    pretrained_model_name: regnetx_008
    spectrogram_backend: torch
    spectrogram_type: spectrogram
model:
  class_path: ml.models.VisionCNN
  init_args:
    freeze: false
    n_output: 1
    lr: 0.000630957
    pretrained_model_name: regnetx_008
    weigh_loss: true
